import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { Input, TextArea, Slider } from '@/components/ui/BaseComponents';
import { Card, CardHeader } from '@/components/ui/AdvancedComponents';
import { cn, MODEL_BADGES, PERFORMANCE_BADGES, validateImageDimensions } from '@/utils';
import { Check } from 'lucide-react';
export const ModelSelector = ({ models, selectedModel, onSelect, compact, }) => {
    if (compact) {
        return (_jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "block text-sm font-medium text-dark-100", children: "Model" }), _jsxs("select", { value: selectedModel?.id || '', onChange: (e) => {
                        const model = models.find((m) => m.id === e.target.value);
                        if (model)
                            onSelect(model);
                    }, className: "input-base w-full", children: [_jsx("option", { value: "", children: "Select a model" }), models.filter((m) => m.installed).map((model) => (_jsx("option", { value: model.id, children: model.displayName }, model.id)))] })] }));
    }
    return (_jsxs("div", { className: "space-y-3", children: [_jsx("label", { className: "block text-sm font-medium text-dark-100", children: "Model" }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-3", children: models.filter((m) => m.installed).map((model) => (_jsx(Card, { hover: true, className: cn('cursor-pointer border-2 transition-all', selectedModel?.id === model.id
                        ? 'border-blue-600 bg-blue-900/20'
                        : 'border-dark-700 hover:border-dark-600'), onClick: () => onSelect(model), children: _jsxs("div", { className: "flex items-start justify-between", children: [_jsxs("div", { className: "flex-1", children: [_jsx("h3", { className: "font-semibold text-dark-100", children: model.displayName }), _jsx("p", { className: "text-sm text-dark-400 mt-1", children: model.description }), _jsxs("div", { className: "flex gap-2 mt-3", children: [_jsx("span", { className: "text-xs px-2 py-1 bg-dark-700 rounded", children: MODEL_BADGES[model.id]?.label || model.name }), _jsx("span", { className: "text-xs px-2 py-1 bg-dark-700 rounded", children: PERFORMANCE_BADGES[model.performance] })] })] }), selectedModel?.id === model.id && (_jsx(Check, { className: "text-blue-600", size: 20 }))] }) }, model.id))) })] }));
};
export const PromptEditor = ({ prompt, onPromptChange, negativePrompt, onNegativePromptChange, templates, }) => {
    const [showTemplates, setShowTemplates] = React.useState(false);
    return (_jsxs(Card, { children: [_jsx(CardHeader, { title: "Prompt", description: "Describe what you want to generate" }), _jsxs("div", { className: "space-y-4", children: [_jsx(TextArea, { value: prompt, onChange: (e) => onPromptChange(e.target.value), placeholder: "e.g., A serene landscape with mountains and a lake at sunset...", maxLength: 2000, showCharCount: true, rows: 4 }), onNegativePromptChange && (_jsx(TextArea, { value: negativePrompt || '', onChange: (e) => onNegativePromptChange(e.target.value), placeholder: "What to avoid in the image...", maxLength: 1000, rows: 2 })), templates && templates.length > 0 && (_jsxs("div", { children: [_jsxs("button", { onClick: () => setShowTemplates(!showTemplates), className: "text-blue-400 hover:text-blue-300 text-sm font-medium", children: [showTemplates ? '▼' : '▶', " Prompt Templates"] }), showTemplates && (_jsx("div", { className: "mt-2 space-y-2", children: templates.map((template) => (_jsxs("button", { onClick: () => {
                                        onPromptChange(template.content);
                                        setShowTemplates(false);
                                    }, className: "w-full text-left px-3 py-2 rounded hover:bg-dark-700 transition-colors text-sm", children: [_jsx("div", { className: "font-medium text-dark-100", children: template.name }), _jsx("div", { className: "text-dark-400 text-xs mt-1", children: template.description })] }, template.id))) }))] }))] })] }));
};
export const GenerationSettings = ({ width, onWidthChange, height, onHeightChange, steps, onStepsChange, cfgScale, onCfgScaleChange, seed, onSeedChange, randomSeed, onRandomSeedChange, count, onCountChange, }) => {
    const dimensions = validateImageDimensions(width, height);
    return (_jsxs(Card, { children: [_jsx(CardHeader, { title: "Generation Settings" }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "grid grid-cols-2 gap-3", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-dark-100 mb-2", children: "Width" }), _jsx(Input, { type: "number", value: width, onChange: (e) => onWidthChange(parseInt(e.target.value, 10)), min: 256, max: 2048, step: 64 })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-dark-100 mb-2", children: "Height" }), _jsx(Input, { type: "number", value: height, onChange: (e) => onHeightChange(parseInt(e.target.value, 10)), min: 256, max: 2048, step: 64 })] })] }), !dimensions.valid && (_jsx("p", { className: "text-red-500 text-sm", children: dimensions.error })), _jsx(Slider, { label: "Steps", min: 1, max: 50, step: 1, value: steps, onChange: (e) => onStepsChange(parseInt(e.target.value, 10)) }), _jsx(Slider, { label: "CFG Scale", min: 1, max: 20, step: 0.5, value: cfgScale, onChange: (e) => onCfgScaleChange(parseFloat(e.target.value)) }), _jsxs("div", { children: [_jsxs("label", { className: "flex items-center gap-2 mb-3", children: [_jsx("input", { type: "checkbox", checked: randomSeed, onChange: (e) => onRandomSeedChange(e.target.checked), className: "w-4 h-4 rounded" }), _jsx("span", { className: "text-sm font-medium text-dark-100", children: "Random Seed" })] }), !randomSeed && (_jsx(Input, { type: "number", value: seed || '', onChange: (e) => onSeedChange(e.target.value ? parseInt(e.target.value, 10) : null), placeholder: "Enter seed" }))] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-dark-100 mb-2", children: "Number of Images" }), _jsx("select", { value: count, onChange: (e) => onCountChange(parseInt(e.target.value, 10)), className: "input-base w-full", children: [1, 2, 3, 4].map((n) => (_jsx("option", { value: n, children: n }, n))) })] })] })] }));
};
