import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useCallback, useState } from 'react';
import { ChevronLeft, ChevronRight, Copy, Download, Heart, Info, X } from 'lucide-react';
import { ImageCard } from '@/components/gallery/ImageCard';
import { formatDate } from '@/utils';
export const ImageGrid = ({ images, emptyMessage, onFavorite, onCopyPrompt }) => {
    const [fullscreenImage, setFullscreenImage] = useState(null);
    const fullscreenIndex = images.findIndex((image) => image.id === fullscreenImage?.id);
    const navigate = useCallback((direction) => {
        const nextIndex = fullscreenIndex + direction;
        if (nextIndex >= 0 && nextIndex < images.length) {
            setFullscreenImage(images[nextIndex]);
        }
    }, [fullscreenIndex, images]);
    if (images.length === 0) {
        return (_jsxs("div", { className: "flex flex-col items-center justify-center py-20 text-center", children: [_jsx("div", { className: "mb-4 flex h-16 w-16 items-center justify-center rounded-2xl border border-dark-700 bg-dark-800", children: _jsx(Info, { size: 24, className: "text-dark-500" }) }), _jsx("p", { className: "font-medium text-dark-300", children: emptyMessage ?? 'No images yet' }), _jsx("p", { className: "mt-1 text-sm text-dark-500", children: "Generated images will appear here" })] }));
    }
    return (_jsxs(_Fragment, { children: [_jsx("div", { className: "masonry-grid", children: images.map((image) => (_jsx("button", { type: "button", className: "masonry-item block w-full text-left", onClick: () => setFullscreenImage(image), children: _jsx(ImageCard, { image: image }) }, image.id))) }), fullscreenImage && (_jsxs("div", { className: "fixed inset-0 z-[100] flex items-center justify-center bg-black/95 p-4 backdrop-blur-md", children: [_jsx("button", { type: "button", onClick: () => setFullscreenImage(null), className: "absolute right-5 top-5 z-10 rounded-xl bg-white/10 p-2 text-white transition-colors hover:bg-white/20", children: _jsx(X, { size: 20 }) }), fullscreenIndex > 0 && (_jsx("button", { type: "button", onClick: () => navigate(-1), className: "absolute left-5 top-1/2 z-10 -translate-y-1/2 rounded-xl bg-white/10 p-2 text-white transition-colors hover:bg-white/20", children: _jsx(ChevronLeft, { size: 24 }) })), fullscreenIndex < images.length - 1 && (_jsx("button", { type: "button", onClick: () => navigate(1), className: "absolute right-5 top-1/2 z-10 -translate-y-1/2 rounded-xl bg-white/10 p-2 text-white transition-colors hover:bg-white/20", children: _jsx(ChevronRight, { size: 24 }) })), _jsxs("div", { className: "flex max-h-screen w-full max-w-6xl flex-col gap-6 overflow-auto p-2 lg:flex-row lg:items-start", children: [_jsx("div", { className: "flex flex-1 items-center justify-center", children: _jsx("img", { src: fullscreenImage.url, alt: fullscreenImage.prompt, className: "max-h-[78vh] max-w-full rounded-2xl shadow-2xl" }) }), _jsxs("aside", { className: "w-full flex-shrink-0 space-y-5 rounded-2xl border border-dark-700 bg-dark-900 p-5 lg:w-80", children: [_jsxs("div", { children: [_jsx("p", { className: "mb-2 text-xs font-semibold uppercase tracking-wider text-dark-500", children: "Prompt" }), _jsx("p", { className: "text-sm leading-relaxed text-dark-300", children: fullscreenImage.prompt })] }), fullscreenImage.negativePrompt && (_jsxs("div", { children: [_jsx("p", { className: "mb-2 text-xs font-semibold uppercase tracking-wider text-dark-500", children: "Negative" }), _jsx("p", { className: "text-sm leading-relaxed text-dark-300", children: fullscreenImage.negativePrompt })] })), _jsx("div", { className: "grid grid-cols-2 gap-3", children: [
                                            { label: 'Model', value: fullscreenImage.model },
                                            { label: 'Size', value: `${fullscreenImage.params.width}x${fullscreenImage.params.height}` },
                                            { label: 'Steps', value: String(fullscreenImage.params.steps) },
                                            { label: 'CFG', value: String(fullscreenImage.params.cfgScale) },
                                            { label: 'Time', value: `${fullscreenImage.generationTime}s` },
                                            { label: 'Created', value: formatDate(fullscreenImage.createdAt) },
                                        ].map(({ label, value }) => (_jsxs("div", { className: "rounded-lg bg-dark-800 p-2.5", children: [_jsx("p", { className: "text-[10px] uppercase tracking-wide text-dark-500", children: label }), _jsx("p", { className: "mt-0.5 truncate text-xs font-medium text-white", children: value })] }, label))) }), _jsxs("div", { className: "flex gap-2", children: [_jsxs("button", { type: "button", onClick: () => onCopyPrompt?.(fullscreenImage.prompt), className: "flex flex-1 items-center justify-center gap-2 rounded-xl border border-dark-700 bg-dark-800 py-2.5 text-sm font-medium text-dark-300 transition-colors hover:text-white", children: [_jsx(Copy, { size: 14 }), "Copy"] }), _jsx("button", { type: "button", onClick: () => onFavorite?.(fullscreenImage), className: `rounded-xl border p-2.5 transition-colors ${fullscreenImage.isFavorite
                                                    ? 'border-red-500/40 bg-red-500/20 text-red-400'
                                                    : 'border-dark-700 bg-dark-800 text-dark-500 hover:text-red-400'}`, children: _jsx(Heart, { size: 16, fill: fullscreenImage.isFavorite ? 'currentColor' : 'none' }) }), _jsx("button", { type: "button", onClick: () => window.open(fullscreenImage.url, '_blank'), className: "rounded-xl border border-indigo-500/30 bg-indigo-500/20 p-2.5 text-indigo-400 transition-colors hover:bg-indigo-500/30", children: _jsx(Download, { size: 16 }) })] })] })] })] }))] }));
};
